### ISSUE TITLE
The Roboto font isn't loaded from bower

### ISSUE THREAD

**Issue by iBeliever** [papyros/papyros.github.io#21]
It's only picking up system fonts, so if you don't have Roboto installed, it defaults to something that looks like Times New Roman.

**Comment by jamesspinella** [comment]
You could add this: @import url(http://fonts.googleapis.com/css?family=Roboto); to main.css below @charset "utf-8". Roboto will be served via Google Fonts, solving the font issue.

Note: If (well, *when*) the Papyros website moves from http to https, you must change the URL aforementioned to also be "https", otherwise you'll encounter a "hey, only some elements on this page are secure!" notification in-browser, and depending, the font won't load.

**Comment by ElliotFriend** [comment]
+1 for Google Fonts. That will reduce the load on the GH Pages servers, too.

**Comment by mralext20** [comment]
so... we can close this now?

**Comment by ElliotFriend** [comment]
I would think so... Although, we're not using bower to install the font. If that's something they were really interested in implementing, it makes sense to keep the issue open.

**Comment by iBeliever** [comment]
I left the issue open until I could confirm on a device that I knew didn't have the Roboto font installed. I verified that it's working, so I'll close this now.
