### ISSUE TITLE
Site logo text on main page springs to next line for width < 340px

### ISSUE THREAD

**Issue by Vogeltak** [papyros/papyros.github.io#42]
This can be fixed by setting styles for `#logo-container` like this:
``` css
/* fixes the real problem */
position: relative;

/* keeps the logo centered */
transform: translateX(-75%);
```

I would fix this myself (already have it done) but I do not know where to properly implement this fix. I just created a new css file and linked it from the `default_light` layout. As this is not a very elegant solution, I though I would ask for your help here.

**Comment by hakarune** [comment]
The problem is justs text size. you don't need to go adding relative and transforms. those can mess up the code. we just need to add `@media only screen and (max-width : 340px) { font-size: 1.6rem; }` to material.min.css:6 (will do it real quick). It will cure the issue until  ~280px screen, but no one should be on something small.

**Comment by Vogeltak** [comment]
> but no one should be on something small. 

Cool, that's what I thought. For the sake of only keeping relevant issues in place, I will close this.
